name: counter-program

services:
  counter:
    image: solana:v0
    platform: linux/amd64
    command: cargo build-bpf --manifest-path "/program/Cargo.toml" --bpf-out-dir "/program/artifacts" -- --locked
    volumes:
      - type: bind
        source: ./program
        target: /program
        read_only: false
    environment:
      BRIDGE_ADDRESS: "Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o"
      EMITTER_ADDRESS: "11111111111111111111111111111115"
